"use client";
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type User={id:string;email:string;name:string;role:string;is_active:boolean};
const roles=['admin','cto','manager','team_member'];
export default function AdminPage(){const [users,setUsers]=useState<User[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<string|null>(null);
async function load(){const r=await fetch(API+'/api/v1/rbac/users',{credentials:'include'});if(r.status===401){window.location.href='/auth?next=/admin';return}if(r.status===403){window.location.href='/';return}const d=await r.json();if(!r.ok){setError(d.detail||'Unable to load users');return}setUsers(d);setLoading(false)}
useEffect(()=>{load()},[]);
async function changeRole(id:string,role:string){setSaving(id);setError('');const r=await fetch(API+`/api/v1/rbac/users/${id}/role`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({role})});const d=await r.json();if(!r.ok){setError(d.detail||'Role update failed')}else setUsers(x=>x.map(u=>u.id===id?d:u));setSaving(null)}
return <main className="main" style={{padding:40,maxWidth:1100,margin:'0 auto'}}><div className="top"><div><div className="eyebrow">Administration</div><h1 className="title">User & Role Management</h1><div className="subtitle">Only Admin and CTO can access this workspace.</div></div><span className="pill">RBAC</span></div>{error&&<div className="answer" style={{marginTop:20}}>{error}</div>}<section className="card" style={{marginTop:20}}>{loading?<p className="subtitle">Loading users…</p>:<div style={{display:'grid',gap:12}}>{users.map(u=><div key={u.id} style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 180px',gap:16,alignItems:'center',padding:'14px 0',borderBottom:'1px solid var(--border)'}}><div><b>{u.name||u.email}</b><div className="subtitle">{u.email}</div></div><div><span className="pill">{u.role.replace('_',' ')}</span></div><select value={u.role} disabled={saving===u.id} onChange={e=>changeRole(u.id,e.target.value)} style={{padding:10,borderRadius:10}}>{roles.map(role=><option key={role} value={role}>{role.replace('_',' ')}</option>)}</select></div>)}</div>}</section></main>}
