"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Brain, CheckCircle2, Code2, Eye, FileText, Monitor, RefreshCw, Square, Target, Timer } from "lucide-react";
type Source = { id: string; name: string; display_id?: string | null; thumbnail?: string | null };
type Analysis = { summary?: string; visible_text?: string; code?: string; language?: string | null; context_type?: string; question?: string | null; confidence?: number; actionable_context?: string };
type State = { active?: boolean; selected_source?: Source | null; sources?: Source[]; last_capture_at?: string | null; last_analysis_at?: string | null; analysis?: Analysis | null; status?: string; error?: string; continuous?: boolean; interval_ms?: number; analyzing?: boolean };
export default function ScreenContextPage() {
 const [state,setState]=useState<State>({status:"idle",sources:[]}); const [loading,setLoading]=useState(false); const [analyzing,setAnalyzing]=useState(false); const [error,setError]=useState(""); const [interval,setIntervalValue]=useState(8);
 async function refresh(){setLoading(true);setError("");try{const r=await window.genquantaa?.getScreenContextSources?.() as State|undefined;if(r)setState(r)}catch(e){setError(e instanceof Error?e.message:"Could not list screen sources.")}finally{setLoading(false)}}
 useEffect(()=>{window.genquantaa?.getScreenContextState?.().then(r=>{if(r){const s=r as State;setState(s);if(s.interval_ms)setIntervalValue(Math.round(s.interval_ms/1000))}});const u=window.genquantaa?.onScreenContextState?.(r=>{const s=r as State;setState(s);if(s.interval_ms)setIntervalValue(Math.round(s.interval_ms/1000))});void refresh();return()=>u?.()},[]);
 async function selectSource(id:string){setLoading(true);setError("");try{const r=await window.genquantaa?.startScreenContext?.(id) as State|undefined;if(r){setState(r);if(r.status==="error")setError(r.error||"Could not select source.")}}catch(e){setError(e instanceof Error?e.message:"Could not start screen context.")}finally{setLoading(false)}}
 async function analyze(){setAnalyzing(true);setError("");try{const r=await window.genquantaa?.analyzeScreenContext?.() as State|undefined;if(r){setState(r);if(r.status==="error")setError(r.error||"Visual analysis failed.")}}catch(e){setError(e instanceof Error?e.message:"Visual analysis failed.")}finally{setAnalyzing(false)}}
 async function toggleContinuous(){setError("");try{const r=state.continuous?await window.genquantaa?.stopContinuousScreenContext?.():await window.genquantaa?.startContinuousScreenContext?.(interval*1000);if(r){const s=r as State;setState(s);if(s.status==="error")setError(s.error||"Could not change continuous capture")}}catch(e){setError(e instanceof Error?e.message:"Could not change continuous capture")}}
 function useInCopilot(){if(!state.analysis)return;try{sessionStorage.setItem("genquantaa_visual_context",JSON.stringify(state.analysis));window.location.href="/live"}catch{setError("Could not transfer visual context to Copilot.")}}
 async function stop(){const r=await window.genquantaa?.stopScreenContext?.() as State|undefined;if(r)setState(r)}
 const sources=state.sources||[];const analysis=state.analysis;const pct=Math.round((analysis?.confidence||0)*100);
 return <main className="main"><div className="top"><div><div className="eyebrow">Screen Context Intelligence · Phase 4</div><h1 className="title">Smart Visual Capture</h1><div className="subtitle">Explicitly select a window or display, then refresh its visual context on a controlled interval for multimodal Copilot analysis.</div></div><span className="pill"><Monitor size={14}/> {state.continuous?`Auto-refresh · ${interval}s`:state.active?"Capture ready":"Not capturing"}</span></div>
 {error&&<div className="card" style={{marginBottom:18}}>{error}</div>}
 <div className="grid"><section><div className="card hero"><div><div className="eyebrow"><Target size={14}/> Source selection</div><h2>Select what GenQuantaa is allowed to analyze.</h2><p className="subtitle">Continuous capture is opt-in, interval-limited, and restricted to the source you explicitly selected. Images are analyzed in memory and are not persisted by the backend.</p></div><div className="actions" style={{marginTop:18}}><button className="secondary" onClick={refresh} disabled={loading||analyzing}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh sources"}</button>{state.active&&<button className="primary" onClick={analyze} disabled={analyzing||state.continuous}><Brain size={16}/>{analyzing?"Analyzing…":"Analyze selected screen"}</button>}{state.active&&<button className={state.continuous?"primary":"secondary"} onClick={toggleContinuous} disabled={analyzing}><Timer size={16}/>{state.continuous?"Stop auto-refresh":"Start auto-refresh"}</button>}{state.active&&<button className="secondary" onClick={stop} disabled={analyzing}><Square size={16}/>Stop context</button>}</div>{state.active&&<div style={{marginTop:16,maxWidth:420}}><label className="muted" htmlFor="interval">Refresh interval: {interval}s</label><input id="interval" type="range" min="5" max="60" step="1" value={interval} onChange={e=>setIntervalValue(Number(e.target.value))} disabled={state.continuous}/><div className="muted" style={{display:"flex",justifyContent:"space-between"}}><small>5s</small><small>60s</small></div></div>}</div>
 <div className="card" style={{marginTop:20}}><div className="eyebrow">Available windows & displays</div>{sources.length===0?<p className="muted">No capture sources found. Use the desktop app and refresh.</p>:<div className="list">{sources.map(s=><div className="row" key={s.id} style={{gap:14,alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:12,flex:1}}>{s.thumbnail?<img src={s.thumbnail} alt="" width={96} height={54} style={{objectFit:"cover",borderRadius:8}}/>:<Monitor size={20}/>}<span><strong>{s.name}</strong><br/><small className="muted">{s.display_id?`Display ${s.display_id}`:"Window"}</small></span></div><button className={state.selected_source?.id===s.id?"primary":"secondary"} onClick={()=>selectSource(s.id)} disabled={loading||analyzing||state.continuous}>{state.selected_source?.id===s.id?"Selected":"Use source"}</button></div>)}</div>}</div>
 {analysis&&<div className="card" style={{marginTop:20}}><div className="eyebrow"><Brain size={14}/> Latest Gemini Vision context</div><h2>{analysis.summary||"Visual context analyzed"}</h2><div className="list" style={{marginTop:14}}><div className="row"><span>Context type</span><b>{analysis.context_type||"unknown"}</b></div><div className="row"><span>Confidence</span><b>{pct}%</b></div><div className="row"><span>Language</span><b>{analysis.language||"—"}</b></div></div>{analysis.question&&<div style={{marginTop:18}}><div className="eyebrow"><FileText size={14}/> Detected question</div><p>{analysis.question}</p></div>}{analysis.visible_text&&<div style={{marginTop:18}}><div className="eyebrow">Visible text</div><pre style={{whiteSpace:"pre-wrap",overflowX:"auto"}}>{analysis.visible_text}</pre></div>}{analysis.code&&<div style={{marginTop:18}}><div className="eyebrow"><Code2 size={14}/> Detected code</div><pre style={{whiteSpace:"pre-wrap",overflowX:"auto"}}>{analysis.code}</pre></div>}{analysis.actionable_context&&<div style={{marginTop:18}}><div className="eyebrow"><CheckCircle2 size={14}/> Copilot context</div><p className="subtitle">{analysis.actionable_context}</p></div>}<div className="actions" style={{marginTop:18}}><button className="primary" onClick={useInCopilot}><Eye size={16}/> Use latest context in Copilot</button></div></div>}
 </section><aside><div className="card"><div className="eyebrow">Capture status</div><div className="list"><div className="row"><span>Permission</span><b>User selected</b></div><div className="row"><span>Capture state</span><b>{state.active?"Ready":"Stopped"}</b></div><div className="row"><span>Auto-refresh</span><b>{state.continuous?`${interval}s`:"Off"}</b></div><div className="row"><span>Selected source</span><b>{state.selected_source?.name||"—"}</b></div><div className="row"><span>Last analysis</span><b>{state.last_analysis_at?new Date(state.last_analysis_at).toLocaleTimeString():"—"}</b></div></div></div><div className="card" style={{marginTop:20}}><div className="eyebrow">Phase 4 boundary</div><p className="subtitle">✓ Explicit source selection<br/>✓ On-demand screenshot capture<br/>✓ Gemini Vision extraction<br/>✓ OCR/code/question classification<br/>✓ Visual confidence scoring<br/>✓ Transfer to Live Copilot<br/>✓ Controlled continuous refresh<br/>✓ Minimum 5-second interval guard<br/>✓ No screenshot persistence<br/>○ Adaptive scene-change detection — later</p></div></aside></div><button className="secondary" style={{marginTop:20}} onClick={()=>{window.location.href="/"}}><ArrowLeft size={16}/>Back to workspace</button></main>;
}
