"use client";
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Brain,BarChart3,Code2,FileText,LayoutDashboard,Mic,Settings2,Sparkles,Upload,CalendarClock,Monitor,Shield,Users,Briefcase,CreditCard} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type NavItem={name:string;icon:typeof LayoutDashboard;path?:string;roles?:string[]};
const baseNav:NavItem[]=[['Dashboard',LayoutDashboard] as NavItem,['Meeting Auto-Session',CalendarClock,'/meeting'] as NavItem,['Screen Context',Monitor,'/screen-context'] as NavItem,['Live Copilot',Mic,'/live'] as NavItem,['Coding',Code2,'/coding'] as NavItem,['Documents',FileText,'/documents'] as NavItem,['Question Bank',BookOpen,'/question-bank'] as NavItem,['Mock Interview',Brain,'/mock-interview'] as NavItem,['Interview History',BarChart3,'/history'] as NavItem,['Security',Shield,'/security'] as NavItem];
export default function Home(){const [tab,setTab]=useState('Dashboard');const [q,setQ]=useState('');const [answer,setAnswer]=useState('');const [loading,setLoading]=useState(false);const [resume,setResume]=useState('No resume uploaded');const [uploading,setUploading]=useState(false);const [role,setRole]=useState('team_member');const inputRef=useRef<HTMLInputElement>(null);
useEffect(()=>{fetch(API+'/api/v1/rbac/roles',{credentials:'include'}).then(async r=>{if(r.status===401){window.location.href='/auth?next=/';return}if(r.ok){const d=await r.json();setRole(d.role||'team_member')}}).catch(()=>{})},[]);
const nav:NavItem[]=[...baseNav,{name:'Manager',icon:Briefcase,path:'/manager',roles:['admin','cto','manager']},{name:'Admin',icon:Users,path:'/admin',roles:['admin','cto']},{name:'Pricing',icon:CreditCard,path:'/pricing',roles:['admin','cto']}].filter(item=>!item.roles||item.roles.includes(role));
async function ask(){if(!q.trim())return;setLoading(true);try{const r=await fetch(API+'/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({message:q})});const d=await r.json();if(r.status===401){window.location.href='/auth?next=/';return}setAnswer(d.answer||d.detail||'No answer returned.')}catch{setAnswer('Backend unavailable. Start the FastAPI server and try again.')}finally{setLoading(false)}}
async function uploadResume(file:File){setUploading(true);try{const body=new FormData();body.append('file',file);const r=await fetch(API+'/api/v1/resume/upload',{method:'POST',body,credentials:'include'});const d=await r.json();if(r.status===401){window.location.href='/auth?next=/';return}if(!r.ok)throw new Error(d.detail||'Upload failed');setResume(`${d.name||'Candidate'} · ${d.skills?.slice(0,5).join(', ')||'skills detected'}${d.experience_years?` · ${d.experience_years} years`:''}`)}catch(e){setResume(e instanceof Error?e.message:'Resume upload failed')}finally{setUploading(false)}}
return <div className="shell"><aside className="side"><div className="brand">GENQUNTAA AI</div><div className="nav">{nav.map(([name,Icon,path])=><button className={tab===name?'active':''} onClick={()=>{if(path)window.location.href=path;else setTab(name as string)}} key={name as string}><Icon size={16} style={{verticalAlign:'-3px',marginRight:10}}/>{name as string}</button>)}</div><div className="sideFooter"><Settings2 size={14}/> Role: <b style={{textTransform:'capitalize'}}>{role.replace('_',' ')}</b><br/>Gemini-powered copilot</div></aside><main className="main"><div className="top"><div><div className="eyebrow">AI interview workspace</div><h1 className="title">{tab}</h1><div className="subtitle">Prepare, practice, and perform with one focused workspace.</div></div><button className="pill"><Sparkles size={14}/> AI ready</button></div><div className="grid"><section><div className="card hero"><div><div className="eyebrow">Real-time copilot</div><h2>Turn every interview question into a clear, structured answer.</h2><p className="subtitle">Your resume and knowledge documents become retrieval context for answers.</p></div><div className="actions"><button className="primary" onClick={()=>window.location.href='/meeting'}><CalendarClock size={16}/> Start Meeting Session</button><button className="secondary" onClick={()=>inputRef.current?.click()}><Upload size={16}/> {uploading?'Uploading…':'Upload Resume'}</button><input ref={inputRef} hidden type="file" accept=".pdf,.txt,.md" onChange={e=>{const f=e.target.files?.[0];if(f)uploadResume(f)}}/></div></div><div className="stats"><div className="stat"><span className="label">Sessions</span><b>24</b></div><div className="stat"><span className="label">Questions</span><b>186</b></div><div className="stat"><span className="label">Practice</span><b>87%</b></div></div><div className="card" style={{marginTop:20}}><div className="eyebrow">Ask GenQuantaa</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="e.g. Explain Azure Data Factory integration runtime"/><button className="primary" onClick={ask}>{loading?'Thinking…':'Ask AI'}</button></div>{answer&&<div className="answer">{answer}</div>}</div></section><aside className="card"><div className="eyebrow">Resume context</div><p className="subtitle">{resume}</p><div className="eyebrow" style={{marginTop:28}}>Workspace</div><p className="subtitle">Meeting auto-session<br/>Screen context capture<br/>Live transcription<br/>Coding copilot<br/>Question bank<br/>Interview history & analytics<br/>AI notes<br/>Documents & knowledge base<br/>Semantic retrieval<br/>AI mock interviews<br/>Session security<br/>{role==='admin'||role==='cto'?<>Administration<br/>Pricing & billing</>:role==='manager'?<>Manager workspace</>:null}</p></aside></div></main></div>}
