"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,BookOpen,ChevronRight,Search,Shuffle} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Question={id:string;category:string;difficulty:string;question:string};
export default function QuestionBank(){const [items,setItems]=useState<Question[]>([]);const [categories,setCategories]=useState<string[]>([]);const [category,setCategory]=useState('');const [difficulty,setDifficulty]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [random,setRandom]=useState<Question|null>(null);
async function load(){setLoading(true);const p=new URLSearchParams();if(category)p.set('category',category);if(difficulty)p.set('difficulty',difficulty);if(search)p.set('search',search);const r=await fetch(API+'/api/v1/question-bank?'+p);const d=await r.json();setItems(d.questions||[]);setLoading(false)}
useEffect(()=>{fetch(API+'/api/v1/question-bank/categories').then(r=>r.json()).then(setCategories);load()},[]);
async function pick(){const r=await fetch(API+'/api/v1/question-bank/random'+(category?`?category=${encodeURIComponent(category)}`:''));const d=await r.json();setRandom(d.question?d:null)}
return <main className="main"><div className="top"><div><div className="eyebrow"><BookOpen size={14}/> Interview preparation</div><h1 className="title">Question Bank</h1><div className="subtitle">Practice technical, project and behavioral questions before your interview.</div></div><button className="secondary" onClick={()=>window.location.href='/' }><ArrowLeft size={16}/> Workspace</button></div><div className="card hero"><div><div className="eyebrow">Random practice</div><h2>{random?.question||'Need a question? Let AI pick one.'}</h2>{random&&<span className="pill">{random.category} · {random.difficulty}</span>}</div><button className="primary" onClick={pick}><Shuffle size={16}/> Random question</button></div><div className="card" style={{marginTop:20}}><div className="composer"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search questions…"/><button className="primary" onClick={load}><Search size={16}/> Search</button></div><div className="actions" style={{marginTop:14}}><select value={category} onChange={e=>{setCategory(e.target.value);setTimeout(load,0)}}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={difficulty} onChange={e=>{setDifficulty(e.target.value);setTimeout(load,0)}}><option value="">All difficulties</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div></div><div style={{marginTop:20}}>{loading?<div className="card">Loading questions…</div>:items.map(q=><div className="card" style={{marginBottom:12}} key={q.id}><div className="eyebrow">{q.category} · {q.difficulty}</div><h3>{q.question}</h3><button className="secondary" onClick={()=>window.location.href='/mock-interview'}>Practice this <ChevronRight size={15}/></button></div>)}{!loading&&!items.length&&<div className="card">No questions match these filters.</div>}</div></main>}
