"use client";
import {useState} from 'react';
import {ArrowLeft,Code2,Play,RotateCcw} from 'lucide-react';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
const starter=`def two_sum(nums, target):\n    seen = {}\n    for i, value in enumerate(nums):\n        complement = target - value\n        if complement in seen:\n            return [seen[complement], i]\n        seen[value] = i\n    return []`;

type Result={language:string;problem:string;approach:string;solution:string;optimized_solution:string;complexity:string;edge_cases:string[];explanation:string;interview_tips:string[];sources?:{filename:string;content:string;score:number}[]};

export default function CodingPage(){
 const [code,setCode]=useState(starter);const [question,setQuestion]=useState('Explain and improve this solution for the Two Sum problem.');const [language,setLanguage]=useState('python');const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 async function analyze(){setLoading(true);setError('');try{const r=await fetch(`${API}/api/v1/coding/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,question,language})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Analysis failed');setResult(d)}catch(e){setError(e instanceof Error?e.message:'Coding analysis failed')}finally{setLoading(false)}}
 return <main className="main"><div className="top"><div><div className="eyebrow">Coding intelligence</div><h1 className="title">Coding Copilot</h1><div className="subtitle">Analyze algorithms, explain code, optimize solutions, and prepare interview talking points.</div></div><span className="pill"><Code2 size={14}/> AI coding mode</span></div>{error&&<div className="card" style={{marginBottom:18}}>{error}</div>}<div className="grid"><section><div className="card"><div className="composer"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Describe the coding problem or ask what the interviewer wants…"/><select value={language} onChange={e=>setLanguage(e.target.value)}><option>python</option><option>javascript</option><option>typescript</option><option>java</option><option>cpp</option><option>sql</option><option>auto</option></select></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} style={{width:'100%',minHeight:430,marginTop:16,fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace',fontSize:14,lineHeight:1.6,padding:18,borderRadius:14,border:'1px solid rgba(0,0,0,.12)',background:'#10110b',color:'#f4f3dc'}}/><div className="actions" style={{marginTop:14}}><button className="primary" onClick={analyze} disabled={loading}><Play size={16}/>{loading?'Analyzing…':'Analyze Code'}</button><button className="secondary" onClick={()=>{setCode('');setResult(null)}}><RotateCcw size={16}/> Clear</button></div></div>{result&&<div className="card" style={{marginTop:20}}><div className="eyebrow">Recommended solution</div><h2>{result.approach}</h2><pre style={{whiteSpace:'pre-wrap',overflowX:'auto'}}>{result.solution}</pre><div className="eyebrow" style={{marginTop:24}}>Optimized solution</div><pre style={{whiteSpace:'pre-wrap',overflowX:'auto'}}>{result.optimized_solution}</pre></div>}</section><aside><div className="card"><div className="eyebrow">Complexity</div><div className="answer" style={{minHeight:80}}>{result?.complexity||'Run analysis to calculate time and space complexity.'}</div></div><div className="card" style={{marginTop:20}}><div className="eyebrow">Explanation</div><p>{result?.explanation||'The copilot will explain the reasoning in interview-friendly language.'}</p></div><div className="card" style={{marginTop:20}}><div className="eyebrow">Edge cases</div>{result?.edge_cases?.length?<ul>{result.edge_cases.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="muted">Important edge cases appear here.</p>}</div><div className="card" style={{marginTop:20}}><div className="eyebrow">Interview tips</div>{result?.interview_tips?.length?<ul>{result.interview_tips.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="muted">How to communicate the solution will appear here.</p>}</div></aside></div><button className="secondary" style={{marginTop:20}} onClick={()=>window.location.href='/'}><ArrowLeft size={16}/> Back to workspace</button></main>;
}
