"use client";
import {useState} from "react";
import {ArrowLeft,Brain,ChevronRight,RefreshCw,Sparkles,Target} from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Result={question:string;question_type:string;difficulty:string;focus_area:string;rationale:string;expected_concepts:string[];follow_up_strategy:string;sequence:number;adaptive:boolean};
export default function Adaptive(){const [sessionId,setSessionId]=useState("");const [role,setRole]=useState("Data Engineer");const [focus,setFocus]=useState("adaptive");const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
async function next(){if(!sessionId.trim()){setError("Enter an interview session ID from Interview History or a live session.");return}setLoading(true);setError("");try{const r=await fetch(`${API}/api/v1/adaptive/sessions/${sessionId.trim()}/next`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_role:role,focus})});if(r.status===401){window.location.href=`/auth?next=/adaptive`;return}const d=await r.json();if(!r.ok)throw Error(d.detail||"Unable to generate next question");setResult(d)}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setLoading(false)}}
return <main className="main"><div className="top"><div><div className="eyebrow">Adaptive interview engine</div><h1 className="title">AI Interviewer</h1><p className="subtitle">Every next question adapts to previous candidate performance, weaknesses, difficulty and role.</p></div><button className="secondary" onClick={()=>window.location.href="/"}><ArrowLeft size={15}/> Workspace</button></div>
<div className="card"><div className="eyebrow"><Target size={14}/> Interview configuration</div><div className="grid" style={{marginTop:14}}><label>Session ID<input value={sessionId} onChange={e=>setSessionId(e.target.value)} placeholder="Paste session UUID" style={{width:"100%",marginTop:6,padding:10}}/></label><label>Target role<input value={role} onChange={e=>setRole(e.target.value)} style={{width:"100%",marginTop:6,padding:10}}/></label><label>Focus<select value={focus} onChange={e=>setFocus(e.target.value)} style={{width:"100%",marginTop:6,padding:10}}><option value="adaptive">Adaptive</option><option value="technical depth">Technical depth</option><option value="system design">System design</option><option value="troubleshooting">Troubleshooting</option><option value="behavioral">Behavioral</option><option value="coding">Coding</option></select></label></div><button className="primary" style={{marginTop:16}} onClick={next} disabled={loading}>{loading?<><RefreshCw size={15}/> Selecting…</>:<><Sparkles size={15}/> Generate next question</>}</button></div>
{error&&<div className="card" style={{marginTop:18}}>{error}</div>}
{result&&<div className="card" style={{marginTop:18}}><div className="eyebrow"><Brain size={14}/> Question {result.sequence} {result.adaptive?"· Adapted to performance":"· Baseline"}</div><h2 style={{marginTop:10}}>{result.question}</h2><div className="row"><span>{result.question_type.replace("_"," ")} · <b style={{textTransform:"capitalize"}}>{result.difficulty}</b></span><span><b>{result.focus_area}</b></span></div><div className="grid" style={{marginTop:18}}><div><h3>Why this question?</h3><p>{result.rationale}</p></div><div><h3>Expected concepts</h3><ul>{result.expected_concepts.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div><div style={{marginTop:14}}><h3>Follow-up strategy</h3><p>{result.follow_up_strategy}</p></div><button className="primary" style={{marginTop:16}} onClick={next}><ChevronRight size={15}/> Choose next question</button></div>}
<div className="card" style={{marginTop:18}}><div className="eyebrow">How adaptation works</div><div className="grid" style={{marginTop:12}}><p><b>Weak answer</b><br/>Targets the missing concept or reduces difficulty.</p><p><b>Strong answer</b><br/>Raises difficulty and probes deeper trade-offs.</p><p><b>No repetition</b><br/>Avoids previously asked questions unless remediation is intentional.</p></div></div></main>}
