"use client";
import {useRef,useState} from 'react';
import {ArrowLeft,Mic,MicOff,Radio,Send,Square} from 'lucide-react';

function pcm16(input:Float32Array){const pcm=new Int16Array(input.length);for(let i=0;i<input.length;i++){const x=Math.max(-1,Math.min(1,input[i]));pcm[i]=x<0?x*0x8000:x*0x7fff;}const bytes=new Uint8Array(pcm.buffer);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(binary)}

export default function LivePage(){
 const ws=useRef<WebSocket|null>(null);const ctx=useRef<AudioContext|null>(null);const processor=useRef<ScriptProcessorNode|null>(null);const source=useRef<MediaStreamAudioSourceNode|null>(null);const stream=useRef<MediaStream|null>(null);
 const [connected,setConnected]=useState(false);const [listening,setListening]=useState(false);const [input,setInput]=useState('');const [answer,setAnswer]=useState('');const [transcript,setTranscript]=useState('');const [error,setError]=useState('');
 function connect(){const api=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';const socket=new WebSocket(api.replace(/^http/,'ws')+'/api/v1/realtime/ws');ws.current=socket;socket.onopen=()=>{setConnected(true);setError('')};socket.onclose=()=>{setConnected(false);setListening(false)};socket.onerror=()=>setError('Live connection failed. Check the backend and GEMINI_API_KEY.');socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='text')setAnswer(v=>v+d.text);if(d.type==='transcript')setTranscript(v=>(v?v+' ':'')+d.text);if(d.type==='transcript_interim')setTranscript(v=>v.split(' ').slice(0,-2).join(' ')+' '+d.text);if(d.type==='turn_complete')setAnswer(v=>v+'\n');if(d.type==='interrupted')setAnswer('');if(d.type==='error')setError(d.message)}}
 async function startMic(){if(!ws.current||ws.current.readyState!==WebSocket.OPEN)return;const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const audio=new AudioContext({sampleRate:16000});ctx.current=audio;const inputNode=audio.createMediaStreamSource(media);const node=audio.createScriptProcessor(2048,1,1);source.current=inputNode;processor.current=node;node.onaudioprocess=e=>{if(ws.current?.readyState===WebSocket.OPEN)ws.current.send(JSON.stringify({type:'audio',data:pcm16(e.inputBuffer.getChannelData(0)),mime_type:'audio/pcm;rate=16000'}))};inputNode.connect(node);node.connect(audio.destination);setListening(true)}
 function stopMic(){processor.current?.disconnect();source.current?.disconnect();stream.current?.getTracks().forEach(t=>t.stop());ctx.current?.close();processor.current=null;source.current=null;stream.current=null;ctx.current=null;ws.current?.send(JSON.stringify({type:'audio_end'}));setListening(false)}
 function send(){if(!input.trim()||!ws.current)return;setAnswer('');ws.current.send(JSON.stringify({type:'text',text:input}));setInput('')}
 return <main className="main"><div className="top"><div><div className="eyebrow">Live session</div><h1 className="title">Real-time Copilot</h1><div className="subtitle">Stream interview audio, transcription and context to Gemini.</div></div><span className="pill"><Radio size={14}/> {connected?'Connected':'Offline'}</span></div>{error&&<div className="card" style={{marginBottom:18}}>{error}</div>}<div className="grid"><section><div className="card hero"><div><div className="eyebrow">Live transcription</div><h2>{transcript||'Your interviewer speech will appear here.'}</h2><p className="subtitle">AI output streams in the panel alongside the transcript.</p></div><div className="actions">{!connected?<button className="primary" onClick={connect}><Radio size={16}/> Connect Live</button>:<button className="secondary" onClick={()=>{stopMic();ws.current?.close()}}><Square size={16}/> End Session</button>}{connected&&<button className={listening?'primary':'secondary'} onClick={listening?stopMic:startMic}>{listening?<MicOff size={16}/>:<Mic size={16}/>} {listening?'Stop microphone':'Start microphone'}</button>}</div></div><div className="card" style={{marginTop:20}}><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Send a question or live context…"/><button className="primary" onClick={send}><Send size={16}/></button></div></div></section><aside className="card"><div className="eyebrow">AI answer</div><div className="answer" style={{minHeight:240}}>{answer||'AI answers will appear here.'}</div><div className="muted" style={{marginTop:18}}>PCM audio is streamed at 16kHz. Gemini Live supports raw 16-bit PCM input and low-latency transcription. citeturn0search4turn0search9</div></aside></div><button className="secondary" style={{marginTop:20}} onClick={()=>window.location.href='/'}><ArrowLeft size={16}/> Back to workspace</button></main>
}