"use client";
import {useState} from 'react';
import {ArrowLeft,Brain,CheckCircle2,ChevronRight,RotateCcw,Sparkles} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Result={answer:string;confidence?:number;key_points?:string[];follow_up?:string;question_type?:string};
const starter=['Tell me about yourself.','Explain a challenging data engineering project you worked on.','How would you design a scalable ETL pipeline in Azure?','What is the difference between Spark repartition and coalesce?','Describe a production incident and how you resolved it.'];
export default function MockInterview(){const [i,setI]=useState(0);const [answer,setAnswer]=useState('');const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [started,setStarted]=useState(false);const [score,setScore]=useState(0);
async function submit(){if(!answer.trim())return;setLoading(true);try{let sid=sessionStorage.getItem('mock_session');if(!sid){const s=await fetch(API+'/api/v1/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Mock Interview',mode:'mock'})}).then(r=>r.json());sid=s.id;sessionStorage.setItem('mock_session',sid)}const r=await fetch(`${API}/api/v1/sessions/${sid}/questions/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript:`Question: ${starter[i]}\nCandidate answer: ${answer}`})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Analysis failed');setResult(d);setScore(v=>v+(d.confidence>=0.7?1:0))}catch(e){setResult({answer:e instanceof Error?e.message:'Unable to evaluate answer'})}finally{setLoading(false)}}
function next(){setI(v=>Math.min(v+1,starter.length-1));setAnswer('');setResult(null)}
function reset(){setI(0);setAnswer('');setResult(null);setScore(0);setStarted(false);sessionStorage.removeItem('mock_session')}
return <main className="main"><div className="top"><div><div className="eyebrow">Practice mode</div><h1 className="title">Mock Interview</h1><div className="subtitle">Practice realistic questions and get structured AI feedback.</div></div><button className="secondary" onClick={()=>window.location.href='/'}><ArrowLeft size={16}/> Workspace</button></div>{!started?<div className="card hero"><div><div className="eyebrow"><Brain size={14}/> AI interviewer</div><h2>Run a focused interview before the real one.</h2><p className="subtitle">Answer five common data-engineering questions. GenQuantaa evaluates each response for relevance, structure and confidence.</p></div><button className="primary" onClick={()=>setStarted(true)}><Sparkles size={16}/> Start Interview</button></div>:<div className="grid"><section><div className="card"><div className="eyebrow">Question {i+1} of {starter.length}</div><h2>{starter[i]}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer as you would say it in an interview…" style={{minHeight:190,width:'100%',marginTop:18,padding:16,borderRadius:14,border:'1px solid #ddd',background:'transparent'}}/><div className="actions" style={{marginTop:16}}><button className="primary" onClick={submit} disabled={loading}>{loading?'Evaluating…':'Submit Answer'}</button>{i>0&&<button className="secondary" onClick={()=>{setI(v=>v-1);setResult(null)}}>Previous</button>}</div>{result&&<div className="answer" style={{marginTop:20}}><div className="eyebrow"><CheckCircle2 size={14}/> AI feedback</div><p><b>Assessment:</b> {result.answer}</p>{result.key_points?.length&&<><b>Key points</b><ul>{result.key_points.map((x,n)=><li key={n}>{x}</li>)}</ul></>}{result.follow_up&&<p><b>Follow-up:</b> {result.follow_up}</p>}<p><b>Confidence:</b> {Math.round((result.confidence||0)*100)}%</p></div>}</div></section><aside><div className="card"><div className="eyebrow">Progress</div><h2>{score}/{i+(result?1:0)||0}</h2><p className="subtitle">Strong answers</p>{result&&i<starter.length-1&&<button className="primary" onClick={next}>Next question <ChevronRight size={16}/></button>}{result&&i===starter.length-1&&<button className="secondary" onClick={reset}><RotateCcw size={16}/> Restart</button>}</div></aside></div>}</main>}
